# Generated by Django 2.2.1 on 2019-05-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('media', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('select', models.CharField(default='', max_length=50)),
                ('price_str', models.CharField(default='', max_length=5)),
                ('price_real', models.BigIntegerField(default=0)),
                ('address', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
