# Generated by Django 2.2.1 on 2019-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20190524_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='const_date',
            field=models.CharField(default=0, max_length=100, verbose_name='준공년월'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='construction_firm',
            field=models.CharField(default=0, max_length=20, verbose_name='건설사'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='household',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='세대수'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='low_high',
            field=models.CharField(default=0, max_length=10, verbose_name='저/고층'),
            preserve_default=False,
        ),
    ]
